### ISSUE TITLE
Client ID must be a non empty string

### ISSUE THREAD

**Issue by ics-bldmgr** [keesschollaart81/AzureCostInsights.Marketplace#10]
I'm using managed identity authentication in the Azure Resource Manager service connection and when I run the build, I get an error saying that the client ID can not be empty. I don't see a field to enter the client ID. Should there be a variable or field to enter this data?

**Comment by keesschollaart81** [comment]
Confirmed. I should be able to implement this like they did here: https://github.com/Microsoft/azure-pipelines-tasks/pull/9419 (for later reference)

I'll have to build/test this, will make this part of the 1.5 release in ~a month.

**Comment by keesschollaart81** [comment]
Now fixed/available with release v1.5.0
