### ISSUE TITLE
issue with Azure Devops Dark Theme

### ISSUE THREAD

**Issue by t2kx** [keesschollaart81/AzureCostInsights.Marketplace#12]
Dark Theme renders combo boxes and other input unreadable in the configuration pane
<img width="589" alt="issue_dark_theme" src="https://user-images.githubusercontent.com/37438394/52281071-916c4500-295d-11e9-83ba-ba4221aa4ea3.png">

**Comment by t2kx** [comment]
tested in Microsoft Edge, latest Insider Version, not tested in standard builds

**Comment by keesschollaart81** [comment]
Now fixed with release v1.5.0
