### ISSUE TITLE
Alter colors of data sets

### ISSUE THREAD

**Issue by Rasmus256** [keesschollaart81/AzureCostInsights.Marketplace#17]
It would be nice to be able to alter the colors of the different data series - We have two data sets that are almost indistinquiable from each other, and we see no way of affecting this..
![image](https://user-images.githubusercontent.com/6584421/53959566-41130f00-40e4-11e9-8157-870395a30a38.png)

**Comment by keesschollaart81** [comment]
Hmm, interesting. I use [randomColor](https://github.com/davidmerfield/randomColor) seeded by the name of the series to get a random (but predictable) color. What does it look like if you tick the 'fill' checkbox under advanced options?

**Comment by Rasmus256** [comment]
Hi, sorry about the late reply. It looks like this:
![image](https://user-images.githubusercontent.com/6584421/55379395-4154cd80-551d-11e9-95c2-cacaa22d1826.png)
I tried to find approximately the same region, but fill makes no differrence since I am using a stacked bar chart, I think? I also tried line charts, stacked or not, filled or not, and it always results in these colors for my data.
I am grouping by Resource Group, so the name of each resource group is what's used for the seed?

**Comment by Rasmus256** [comment]
As @keesschollaart81 pointed out, the colors are picked based on the name of the series. I found a way around this by using tags instead of resource groups - Since tags can be any text, and the color is randomly generated from this, fiddling with the tags can dramatically increase readability in the chart :)

**Comment by keesschollaart81** [comment]
Hehe. Nice solution, thanks for working around this, since I could not thing of a easy solution :-)
