### ISSUE TITLE
Exclude all except category in the chart?

### ISSUE THREAD

**Issue by loopfish** [keesschollaart81/AzureCostInsights.Marketplace#9]
I know you can exclude a category by selecting it on it in the Y-axis, but how about the ability to ONLY show that category, and deselect all others, perhaps by control + left-clicking?

**Comment by keesschollaart81** [comment]
Do you mean the behaviour showed in this JSFiddle?

http://jsfiddle.net/km0bpq9s/

**Comment by loopfish** [comment]
@keesschollaart81  yes, exactly like that :)

**Comment by keesschollaart81** [comment]
Implemented in v1.5.0, not with ctrl but with shift (since ctrl+click is hard in OSX), available after 1wk acc-testing.

**Comment by keesschollaart81** [comment]
Now available with release v1.5.0
